### ISSUE TITLE
unable to log into bambu cloud 

### ISSUE THREAD

**Issue by jeffknotaclue** [bigtreetech-beta/PandaTouch-Support#1]
unable to log into bambu cloud on panda touch as bambu expects a auth code entry. no option for this at moment only email and password

**Comment by jonny-happy** [comment]
> unable to log into bambu cloud on panda touch as bambu expects a auth code entry. no option for this at moment only email and password
Please use this new firmware
https://github.com/bigtreetech-beta/PandaTouch-Support/tree/main/V1.0.6/V1.0.5.1
